spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/CanineClientDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: CanineClientDB-Pool
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  flyway:
    enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



#Show SQL
#spring.jpa.properties.hibernate.show_sql=true
#Format SQL
#spring.jpa.properties.hibernate.format_sql=true
#Show bind values
#logging.level.org.hibernate.orm.jdbc.bind=trace


